# Generated by Django 6.1 on 2026-08-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_or_voter_no', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('alias', models.CharField(blank=True, help_text='Street Name / Alias', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('village_province', models.CharField(help_text='Origin Village / District / Province', max_length=150)),
                ('residential_address', models.TextField(help_text='Current Madang Residence')),
                ('identifying_marks', models.TextField(blank=True, help_text='Scars, Tattoos, Amputations')),
                ('mugshot', models.ImageField(blank=True, null=True, upload_to='mugshots/%Y/%m/')),
                ('fingerprint_record_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
