# Generated by Django 6.1 on 2026-09-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_complaint_alter_case_status_alter_case_suspect'),
        ('suspects', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
    model_name='suspect',
    name='suspect_number',
    field=models.CharField(
        blank=True,
        null=True,
        max_length=30,
        unique=True,
    ),
        ),

        migrations.AddField(
            model_name='suspect',
            name='suspect_role',
            field=models.CharField(
                choices=[
                    ('MAIN', 'Main Suspect'),
                    ('CO', 'Co-Suspect'),
                    ('POI', 'Person of Interest'),
                ],
                default='MAIN',
                max_length=20,
            ),
        ),

        migrations.AddField(
            model_name='suspect',
            name='village',
            field=models.CharField(
                blank=True,
                max_length=100,
            ),
        ),

        migrations.AlterField(
            model_name='suspect',
            name='alias',
            field=models.CharField(
                blank=True,
                help_text='Known nickname or alias',
                max_length=100,
            ),
        ),

        migrations.AlterField(
            model_name='suspect',
            name='identifying_marks',
            field=models.TextField(
                blank=True,
                help_text='Scars, tattoos, birthmarks or other identifying features',
            ),
        ),

        migrations.AlterField(
            model_name='suspect',
            name='residential_address',
            field=models.TextField(
                help_text='Current residential address',
            ),
        ),
    ]