# Generated by Django 6.1 on 2026-09-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_complaint_alter_case_status_alter_case_suspect'),
        ('suspects', '0002_remove_suspect_village_province_suspect_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect',
            name='village_province',
        ),
        migrations.AddField(
            model_name='suspect',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suspect_records', to='cases.case'),
        ),
        migrations.AddField(
            model_name='suspect',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='suspect',
            name='id_type',
            field=models.CharField(blank=True, choices=[('NATIONAL_ID', 'National ID'), ('VOTER_ID', 'Voter ID'), ('PASSPORT', 'Passport'), ('DRIVER_LICENSE', "Driver's License"), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='middle_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='suspect',
            name='nationality',
            field=models.CharField(default='Papua New Guinean', max_length=60),
        ),
        migrations.AddField(
            model_name='suspect',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='suspect',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='suspect',
            name='province',
            field=models.CharField(default='Madang', max_length=100),
        ),
    ]
