# Generated by Django 6.1 on 2026-09-13 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_district_alter_policestation_district'),
        ('suspects', '0003_remove_suspect_village_province_suspect_case_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suspects_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspect',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_suspects', to='stations.policestation'),
        ),
    ]
