# Generated by Django 6.1 on 2026-08-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATION', 'Under Investigation'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('COURT', 'Referred to Court')], default='OPEN', max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cases', to=settings.AUTH_USER_MODEL)),
                ('investigating_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigated_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
