# Generated by Django 6.1 on 2026-08-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('records', '0001_initial'),
        ('stations', '0001_initial'),
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='offence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='records.criminaloffence'),
        ),
        migrations.AddField(
            model_name='case',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='stations.policestation'),
        ),
        migrations.AddField(
            model_name='case',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='suspects.suspect'),
        ),
    ]
