# Generated by Django 6.1 on 2026-08-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='arrest_records',
            field=models.ManyToManyField(blank=True, related_name='cases', to='records.arrestrecord'),
        ),
    ]
