# Generated by Django 6.1 on 2026-08-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_arrest_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='arrest_records',
        ),
    ]
