# Generated by Django 6.1 on 2026-09-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_case_arrest_records'),
        ('complaints', '0001_initial'),
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='complaints.complaint'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATION', 'Under Investigation'), ('WARRANT', 'Warrant Requested'), ('ARRESTED', 'Arrested'), ('CUSTODY', 'In Custody'), ('FILE_PREPARED', 'Case File Prepared'), ('PROSECUTION', 'Submitted to Prosecution'), ('CLOSED', 'Closed')], default='OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='suspects.suspect'),
        ),
    ]
