# Generated by Django 6.1 on 2026-09-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_complaint_alter_case_status_alter_case_suspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
    ]
