# Generated by Django 6.1 on 2026-09-01 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_remove_case_arrest_records'),
        ('suspects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('objectives', models.TextField(blank=True, help_text='Objectives of the investigation.')),
                ('findings', models.TextField(blank=True, help_text='Investigator findings.')),
                ('investigator_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned for Further Investigation'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='ASSIGNED', max_length=30)),
                ('start_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('commander_approved_at', models.DateTimeField(blank=True, null=True)),
                ('commander_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investigation', to='cases.case')),
                ('commander_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_investigations', to=settings.AUTH_USER_MODEL)),
                ('lead_investigator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_investigations', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='suspects.suspect')),
            ],
        ),
    ]
