# Generated by Django 6.1 on 2026-09-06 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_complaint_alter_case_status_alter_case_suspect'),
        ('investigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='case',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='commander_approved_by',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='lead_investigator',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='suspect',
        ),
        migrations.CreateModel(
            name='InvestigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_date', models.DateField()),
                ('activity', models.CharField(help_text='Brief description of the investigation activity', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('findings', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('investigation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='cases.case')),
                ('investigating_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=150)),
                ('statement_type', models.CharField(choices=[('VICTIM', 'Victim'), ('WITNESS', 'Witness'), ('SUSPECT', 'Suspect'), ('OTHER', 'Other')], max_length=20)),
                ('statement_date', models.DateField()),
                ('statement_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('statement', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='statements/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='cases.case')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
