# Generated by Django 6.1 on 2026-09-06 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_remove_investigation_case_and_more'),
        ('prosecution', '0002_alter_prosecution_investigation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investigation',
        ),
    ]
