# Generated by Django 6.1 on 2026-09-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_division_alter_user_role_user_division'),
        ('stations', '0002_district_alter_policestation_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stations.district'),
        ),
    ]
