# Generated by Django 6.1 on 2026-09-01 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0002_arrestrecord_case'),
        ('stations', '0002_district_alter_policestation_district'),
        ('suspects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DETAINED', 'Detained'), ('BAIL', 'Released on Bail'), ('COURT_REMAND', 'Remanded to Court'), ('TRANSFERRED', 'Transferred'), ('RELEASED', 'Released'), ('PRISON', 'Transferred to Prison')], default='DETAINED', max_length=30)),
                ('cell_number', models.CharField(blank=True, max_length=30)),
                ('detention_start', models.DateTimeField()),
                ('detention_end', models.DateTimeField(blank=True, null=True)),
                ('bail_amount_pgk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bail_receipt_number', models.CharField(blank=True, max_length=50)),
                ('transfer_destination', models.CharField(blank=True, max_length=200)),
                ('release_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_records', to='records.arrestrecord')),
                ('custody_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_records', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_records', to='stations.policestation')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_records', to='suspects.suspect')),
            ],
        ),
    ]
