# Generated by Django 6.1 on 2026-09-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodyrecord',
            name='station',
        ),
        migrations.RemoveField(
            model_name='custodyrecord',
            name='suspect',
        ),
    ]
