# Generated by Django 6.1 on 2026-09-17 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0003_province_alter_district_province'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('total_complaints', models.PositiveIntegerField(default=0)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('total_open_cases', models.PositiveIntegerField(default=0)),
                ('total_investigation_cases', models.PositiveIntegerField(default=0)),
                ('total_warrant_requests', models.PositiveIntegerField(default=0)),
                ('total_arrests', models.PositiveIntegerField(default=0)),
                ('total_in_custody', models.PositiveIntegerField(default=0)),
                ('total_released', models.PositiveIntegerField(default=0)),
                ('total_evidence', models.PositiveIntegerField(default=0)),
                ('total_prosecution_cases', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True, help_text='Monthly operational summary.')),
                ('operational_notes', models.TextField(blank=True, help_text='Important operational activities and observations.')),
                ('challenges', models.TextField(blank=True, help_text='Challenges faced during the reporting period.')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations from the Station Commander.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('RETURNED', 'Returned'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reports', to='stations.district')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reports_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reports', to='stations.policestation')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'station'), name='unique_monthly_report_per_station')],
            },
        ),
    ]
