# Generated by Django 6.1 on 2026-08-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('suspects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalOffence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('PERSON', 'Offences Against Person (Assault, Homicide)'), ('PROPERTY', 'Property Crimes (Stealing, B&E, Arson)'), ('DRUGS', 'Dangerous Drugs & Homebrew'), ('PUBLIC', 'Public Disorder & Summary Offences'), ('FRAUD', 'Fraud & Financial Crimes')], default='PUBLIC', max_length=20)),
                ('penalty_summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArrestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrest_tracking_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('occurrence_book_no', models.CharField(max_length=50, verbose_name='OB Number')),
                ('arrest_datetime', models.DateTimeField()),
                ('arrest_location', models.CharField(help_text='e.g. Kalibobo, Modilon Road, Meiro Market', max_length=200)),
                ('reason_for_arrest', models.TextField()),
                ('property_seized', models.TextField(blank=True, help_text='Itemized confiscated belongings')),
                ('physical_condition_at_intake', models.TextField(blank=True, help_text='Injuries / Medical observations')),
                ('custody_status', models.CharField(choices=[('DETAINED', 'In Custody (Holding Cell)'), ('BAILED_POLICE', 'Police Bail Granted'), ('COURT_BAIL', 'Remanded to Court'), ('TRANSFERRED', 'Transferred to Beon Prison / Hospital'), ('RELEASED', 'Released without Charge')], default='DETAINED', max_length=25)),
                ('cell_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bail_amount_pgk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bail_receipt_no', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arresting_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrests_made', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='station_arrests', to='stations.policestation')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrests', to='suspects.suspect')),
                ('offences', models.ManyToManyField(related_name='linked_arrests', to='records.criminaloffence')),
            ],
        ),
    ]
