# Generated by Django 6.1 on 2026-08-28 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_case_arrest_records'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrestrecord',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrest_records', to='cases.case'),
        ),
    ]
