# Generated by Django 6.1 on 2026-09-02 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_district_alter_policestation_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(max_length=30, unique=True)),
                ('complainant_name', models.CharField(max_length=150)),
                ('complainant_phone', models.CharField(blank=True, max_length=30)),
                ('complainant_address', models.TextField(blank=True)),
                ('complaint_type', models.CharField(default='GENERAL', max_length=100)),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('CONVERTED', 'Converted to Case'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints_created', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='stations.policestation')),
            ],
        ),
    ]
