# Generated by Django 6.1 on 2026-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complainant_role',
            field=models.CharField(choices=[('VICTIM', 'Victim'), ('WITNESS', 'Witness'), ('VICTIM_WITNESS', 'Victim & Witness'), ('OTHER', 'Other / Complainant')], default='OTHER', max_length=30),
        ),
    ]
