# Generated by Django 6.1 on 2026-09-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_complainant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complainant_statement',
            field=models.TextField(blank=True, help_text='Statement provided from the perspective of the person reporting the complaint.'),
        ),
        migrations.CreateModel(
            name='ComplaintWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('statement', models.TextField(help_text='Record what the witness personally saw or heard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='complaints.complaint')),
            ],
        ),
    ]
