# Generated by Django 6.1 on 2026-08-28 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_arrest_records'),
        ('warrant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrant',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warrants', to='cases.case'),
        ),
    ]
