# Generated by Django 6.1 on 2026-09-01 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_remove_case_arrest_records'),
        ('investigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prosecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prosecution_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted for Prosecution'), ('UNDER_REVIEW', 'Under Review'), ('RETURNED', 'Returned for Further Information'), ('READY_FOR_COURT', 'Ready for Court'), ('COMMITTAL', 'Committal Proceedings'), ('SUMMARY_TRIAL', 'Summary Trial'), ('REFERRED', 'Referred to Court'), ('COMPLETED', 'Prosecution Completed'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=30)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('case_file_complete', models.BooleanField(default=False)),
                ('evidence_reviewed', models.BooleanField(default=False)),
                ('investigation_reviewed', models.BooleanField(default=False)),
                ('arrest_reviewed', models.BooleanField(default=False)),
                ('warrant_reviewed', models.BooleanField(default=False)),
                ('custody_reviewed', models.BooleanField(default=False)),
                ('committal_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=30)),
                ('committal_date', models.DateField(blank=True, null=True)),
                ('committal_notes', models.TextField(blank=True)),
                ('summary_trial_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=30)),
                ('summary_trial_date', models.DateField(blank=True, null=True)),
                ('summary_trial_notes', models.TextField(blank=True)),
                ('review_comments', models.TextField(blank=True)),
                ('return_reason', models.TextField(blank=True)),
                ('decision', models.TextField(blank=True)),
                ('forwarded_to_court', models.BooleanField(default=False)),
                ('forwarded_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prosecution', to='cases.case')),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prosecutions', to='investigation.investigation')),
                ('prosecutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prosecutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
