# Generated by Django 6.1 on 2026-09-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_remove_investigation_case_and_more'),
        ('prosecution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosecution',
            name='investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prosecutions', to='investigation.investigationrecord'),
        ),
    ]
