# Generated by Django 6.1 on 2026-09-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosecution', '0002_alter_prosecution_investigation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prosecution',
            options={'ordering': ['-updated_at']},
        ),
    ]
