# Generated by Django 6.1 on 2026-09-01 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_remove_case_arrest_records'),
        ('records', '0002_arrestrecord_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_number', models.CharField(max_length=50, unique=True)),
                ('evidence_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('PHYSICAL', 'Physical Evidence'), ('DIGITAL', 'Digital Evidence'), ('PHOTOGRAPH', 'Photograph'), ('VIDEO', 'Video'), ('AUDIO', 'Audio Recording'), ('WEAPON', 'Weapon'), ('DRUG', 'Drug / Substance'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location_found', models.CharField(max_length=200)),
                ('date_collected', models.DateTimeField()),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('IN_STORAGE', 'In Storage'), ('TRANSFERRED', 'Transferred'), ('SUBMITTED_COURT', 'Submitted to Court'), ('RETURNED', 'Returned'), ('DISPOSED', 'Disposed')], default='COLLECTED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='records.arrestrecord')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='cases.case')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_collected', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
